### ISSUE TITLE
char은 char* 혹은 char []과는 다릅니다.

### ISSUE THREAD

**Issue by DPS0340** [Seia-Soto/cl-indexes#1]
char은 'a'와 같이 한 글자만을 담을 수 있고요,
char*이나 char []은 "hello world" 같이 문자열을 담을 수 있는, 즉 char의 배열입니다.
혹시 모르셨나요? ㅎ
그리고 문자열을 출력할때는 %s를 사용해야 합니다.
개인적으로 char*을 사용하는걸 추천드립니다. char []은 범위 정하기가 살짝 귀찮거든요.

**Comment by DPS0340** [comment]
이탤릭체 문법으로 나왔네요. char 애스터리스크입니다. 포인터죠.

**Comment by Seia-Soto** [comment]
- CPP는 이 저장소에서 다루지 않습니다.

지금보니 해당 파일에 포인터 배열로 선언되어 있는 것이 아니라 문자로만 선언되어 있네요, 제보 감사합니다.

**Comment by Seia-Soto** [comment]
아, 그리고 다음에 이슈를 남기실 때는 레퍼런스도 같이 부탁드립니다.
