### ISSUE TITLE
대입 연산자를 while에 쓰면 잘못된 결과가 일어날 수 있습니다.

### ISSUE THREAD

**Issue by DPS0340** [Seia-Soto/cl-indexes#2]
대입 연산자는 단순히 대입만 하지만, 좌항의 값을 리턴합니다.
지금 while 코드를 실행시켜보시면 뭔가 이상할 거예요.
왜냐하면 i=0이 시행되면서 0을 리턴하면서 false로 판단되었고, 그래서 첫번째 while문은 실행되지 않습니다.
그리고 두번째 do while문은 무한 루프에 빠지는데요, i=1이 시행되면서 1을 반환하였고, 0이 아닌 정수형은 true로 판단하기 때문입니다.
특이한 오류네요.
비교 연산자 쓰세요. ==로 바꾸세요.

**Comment by Seia-Soto** [comment]
타 언어와 달리 C는 if state에서 변수를 정의하면 해당 변수의 값을 정의 시에는 false를 반환하는군요. 비교 연산자에서 오타나 실수로 대입으로 변경된게 아니라 다른 type-less 언어의 경험에서 나온 실수인 것 같습니다.

원래 예상했던 결과는 callback이 나오는 조건으로 ``i = 0``에서 해당 변수의 선언과 정의가 성공했다는 의미로 ``true``를 반환하여 loopback에 빠지는 것이었습니다만 성급했네요.

``while``과 ``do...while``의 예가 서로 뒤 바뀐 것 같습니다. 이슈 열어주셔서 감사합니다.
